name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup GHC
      uses: haskell-actions/setup@e09ab5080aed999b46591720b1be129e00e0eef5 # v2.8.0
      with:
        ghc-version: '8.4.1'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y liblmdb-dev libpcre3-dev

    - name: Cache dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal') }}

    - name: Build
      run: |
        cabal update
        cabal build -j
